project:
  type: website
  output-dir: docs  
  render:
    - "*.qmd"
    - "resource/*.qmd"
    - "workshop/*.qmd"  
    - "slides/*.qmd"
    
execute:
  freeze: auto
  
website:
  title: "EPA PCE: Workshops"
  page-navigation: true
  reader-mode: true  
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: workshop/index.qmd
        text: Workshops
      - href: resource/index.qmd
        text: Resources

  sidebar:
    - title: "Workshops"
      contents:
        - section: "Overview"
          contents:
            - href: workshop/index.qmd
              text: "🏠 Home"
        - section: "Workshops"
          contents:
          - text: "Workshop 01: Define"
            href: workshop/w01.qmd
          - text: "Workshop 02: Alternatives"
            href: workshop/w02.qmd
          - text: "Workshop 03: Criteria"
            href: workshop/w03.qmd
          - text: "Workshop 04: Outcomes"
            href: workshop/w04.qmd
          - text: "Workshop 05: Trade-offs"
            href: workshop/w05.qmd
          - text: "Workshop 06: Individual Memo"
            href: workshop/w06.qmd
format:
  html:
    author: EPA Teaching Team
    date-format: "DD MMMM YYYY"

    theme:
      light: 
        - journal
        - css/custom.scss
    css: 
      - css/custom_style.css

